# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailog', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
    ]
