# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='createdon',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='signup',
            name='updatedon',
            field=models.DateTimeField(default=None),
        ),
    ]
