# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0003_auto_20170630_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='updatedon',
        ),
        migrations.AlterField(
            model_name='signup',
            name='createdon',
            field=models.DateTimeField(),
        ),
    ]
