# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0004_auto_20170630_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='createdon',
        ),
        migrations.AddField(
            model_name='signup',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
