# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0005_auto_20170630_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
