# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0006_auto_20170630_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='timestamp',
            new_name='createdon',
        ),
    ]
