# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0007_auto_20170630_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='createdon',
        ),
        migrations.AddField(
            model_name='signup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 30, 11, 15, 23, 983147)),
        ),
    ]
