# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0007_auto_20170630_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='emailog',
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='signup',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
