# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0008_auto_20170630_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='created',
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
