# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 11:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0008_auto_20170630_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 30, 11, 17, 13, 758315)),
        ),
    ]
