# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0008_auto_20170708_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
    ]
