# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0010_signup_createdon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='createdon',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
