# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0012_auto_20170630_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
