# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0013_auto_20170630_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
