# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0014_signup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signup',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signup',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=b'', width_field='width'),
        ),
    ]
