# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0015_auto_20170702_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='height',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='width',
        ),
        migrations.AlterField(
            model_name='signup',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
