# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0018_signup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='user',
        ),
    ]
